all:
	cd lol;make clean;make;make install;cd ..
	cd lol_dbf;make clean;make;make install;cd ..
	cd tools;make clean;make;make install;cd ..
	cd logserver;make clean;make;make install;cd ..
	cd examples;make clean;make;make install;cd ..
clean:
	cd lol;make clean;cd ..
	cd lol_dbf;make clean;cd ..
	cd tools;make clean;cd ..
	cd logserver;make clean;cd ..
	cd examples;make clean;cd ..
